# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, firmware ? null, modulesPath ? null, ... }:

{
  imports = if modulesPath != null then [ "${modulesPath}/installer/scan/not-detected.nix" ] else [];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # only set peripheralFirmwareDirectory when firmware was passed via specialArgs
  # (specialArgs provides `firmware` from flake.nix; it may be null)
  hardware = lib.optionalAttrs (firmware != null) {
    asahi.peripheralFirmwareDirectory = firmware;
  }; # existing hardware attrs are merged by the NixOS module system

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;
  boot.extraModprobeConfig = ''
    options hid_apple iso_layout=1
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fab9fa18-5a11-41a9-a68f-8783869e95f6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/648B-1DF2";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
