{
 "title": "Anubis",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"anubis|nginx\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Anubis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests handled",
   "type": "stat",
   "description": "Total number of requests handled on the selected interval",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(anubis_policy_results{instance=~\"$instance\",job=\"anubis\"}[$__range]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Requests allowed",
   "type": "stat",
   "description": "Requests allowed to pass through to the upstream server",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anubis_proxied_requests_total{instance=~\"$instance\",job=\"anubis\"}) - sum(anubis_proxied_requests_total{instance=~\"$instance\",job=\"anubis\"} offset $__range)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\", job=\"anubis\", action='ALLOW'}[$__rate_interval]))",
     "legendFormat": "Allowed"
    },
    {
     "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\", job=\"anubis\", action=\"DENY\"}[$__rate_interval]))",
     "legendFormat": "Denied"
    },
    {
     "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\", job=\"anubis\", action=\"CHALLENGE\"}[$__rate_interval]))",
     "legendFormat": "Challenged"
    }
   ]
  },
  {
   "title": "Verdicts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (increase(anubis_policy_results{instance=~\"$instance\", job=\"anubis\"}[$__range]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Challenge results",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anubis_challenges_validated{instance=~\"$instance\",job=\"anubis\"}[$__range])",
     "legendFormat": "Validated"
    },
    {
     "expr": "increase(anubis_failed_validations{instance=~\"$instance\",job=\"anubis\"}[$__range])",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum by(job, instance) (increase(anubis_challenges_issued{job=\"anubis\",instance=~\"$instance\"}[$__range])) - increase(anubis_challenges_validated{job=\"anubis\",instance=~\"$instance\"}[$__range]) - increase(anubis_failed_validations{job=\"anubis\",instance=~\"$instance\"}[$__range])",
     "legendFormat": "No response"
    }
   ]
  }
 ]
}